sudo: required
dist: trusty

language: php
php:
    - 7.2
env:
    - NODEJS_VERSION=8.x

before_install:
    - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODEJS_VERSION}" | sudo -E bash -
    - sudo apt-get install -y nodejs

install:
    - composer install
    - yarn install

before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead;'
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed
    - php artisan storage:link
    - yarn prod
    - php artisan serve &

script:
    - vendor/phpunit/phpunit/phpunit
